name: Notify due books (every 6hrs)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger notification job
        run: |
          curl -X POST "https://your-domain.vercel.app/api/notify-due-books" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -d '{}'
